### ISSUE TITLE
Terraform not showing on tasks after installed to Azure devops organization 

### ISSUE THREAD

**Issue by AhalimZaki** [microsoft/azure-pipelines-terraform#80]
Hello,
I was doing a CD and wanted to add Terraform task and yet it keeps showing as a grey button that means it’s already installed but I can’t use it .

So far I have tried to fix this issue.
Re-install the terraform.
Created another Project in the same organization, but still the same issue.
Created another organization, now i can use it.
Signed up with another email and i can use it as well.

my conclusion is that i have a bug in my organization, what can i do to fix this issue?

![B8c25d435528a4de8a43b203d5cb078be637960811209050727_terra](https://user-images.githubusercontent.com/23334080/184554600-f6da2700-93ff-47fb-8363-c140abe6f230.jpg)

**Comment by mericstam** [comment]
Hi I have tried to recreate this issue but unable to replicate it. Can you try to uninstall the extension, wait for a couple of hours or if possible 24 hours and then reinstall?

**Comment by AhalimZaki** [comment]
Sure, I still have that organization untouched for troubleshooting I will try and give you my feedback.

**Comment by AhalimZaki** [comment]
Well so far I have deleted the plugin and re-installed it again still the same issue time frame between uninstalling and reinstalling terraform is more than 24 hour, If you can't replicate the issue I can give you access to this organization I don't mind doing that, since this issue is only available on this organization, I have already done what I wanted with terraform in another organization.
If you want access to the organization with the problem please send me your email @ a.halimzaki@gmail.com to give you access permission.

**Comment by mericstam** [comment]
my conclusion is that this issue you are facing is not related to the terraform extension in itself.
I do not have access to Azure DevOps service backend so I cannot fault trace this further and it is a bit out of scope for the terraform extension code base.

Hämta Outlook för iOS<https://aka.ms/o0ukef>
________________________________
Från: HalimZaki ***@***.***>
Skickat: Tuesday, August 30, 2022 4:22:35 PM
Till: microsoft/azure-pipelines-terraform ***@***.***>
Kopia: Manuel Ericstam ***@***.***>; Comment ***@***.***>
Ämne: Re: [microsoft/azure-pipelines-terraform] Terraform not showing on tasks after installed to Azure devops organization (Issue #80)


Well so far I have deleted the plugin and re-installed it again still the same issue time frame between uninstalling and reinstalling terraform is more than 24 hour, If you can't replicate the issue I can give you access to this organization I don't mind doing that, since this issue is only available on this organization, I have already done what I wanted with terraform in another organization.
If you want access to the organization with the problem please send me your email @ ***@***.******@***.***> to give you access permission.

**Comment by mericstam** [comment]
closing this as it is not an issue with the extension
Br
Manuel
